name: 'Custom Slack Message'      
description: 'Slack Message'      
inputs:
  slack_webhook: 
    required: true
    default: ''
  type: 
    required: true
    default: ''
  token:
    required: true
    default: ''
  slack_color:
    required: false
    default: ''
  title:
    required: false
    default: ''
  environment:
    required: false
    default: ''
    
branding:
  icon: 'award'  
  color: 'blue'

runs:
  using: 'docker'                 
  image: 'Dockerfile'             
  args:
    - ${{ inputs.type }}  # pr, build, deploy
    - ${{ inputs.slack_webhook }}
    - ${{ inputs.token }} # git token  
    - ${{ inputs.slack_color }}
    - ${{ inputs.title }}
    - ${{ inputs.environment }} 
