name: 'Custom Slack Message'      
description: 'Slack Message'      
inputs:
  slack_webhook: 
    required: true
    default: ''
  type: 
    required: true
    default: ''
  token:
    required: true
    default: ''
  pr_number:
    required: false
    default: ''
  slack_color:
    required: false
    default: ''
  title:
    required: false
    default: ''
  environment:
    required: false
    default: ''

runs:
  using: 'docker'                 
  image: 'Dockerfile'             
  args:
    - ${{ inputs.type }}  # pr, build, deploy
    - ${{ inputs.slack_webhook }}
    - ${{ inputs.token }} # git token
    - ${{ inputs.pr_number}}  
    - ${{ inputs.slack_color }}
    - ${{ inputs.title }}
    - ${{ inputs.environment }} 