name: 'Custom Slack Message'               # action 이름
description: 'Slack Message'                # 간단한 설명
inputs:
  SLACK_WEBHOOK: 
    required: true
    default: ''
  TYPE: 
    required: true
    default: ''
  PR_NUMBER: 
    required: true
    default: ''
runs:
  using: 'docker'                 # 도커 사용 명시
  image: 'Dockerfile'             # Dockerfile을 이용하여 이미지 생성
  args:                           # docker run 에서 넘길 파라미터
    - ${{ inputs.SLACK_WEBHOOK }}
    - ${{ inputs.TYPE }}
    - ${{ inputs.PR_NUMBER }}