name: 'Custom Slack Message'               # action 이름
description: 'Slack Message'                # 간단한 설명
inputs:
  slack_webhook: 
    required: true
    default: ''
  type: 
    required: true
    default: ''
  token:
    required: true
    default: ''
  repo_name:
    required: false
    default: ''
  pr_number: 
    required: false
    default: ''
  job_status:
    requried: false
    default: ''

runs:
  using: 'docker'                 # 도커 사용 명시
  image: 'Dockerfile'             # Dockerfile을 이용하여 이미지 생성
  env: 
    type: ${{ inputs.type }}
    slack_webhook: ${{ inputs.slack_webhook }}
    token: ${{ inputs.token }}
    pr_number: ${{ inputs.pr_number }}