name: 'Custom Slack Message'               # action 이름
description: 'Slack Message'                # 간단한 설명
inputs:
  slack_webhook: 
    required: true
    default: ''
  type: 
    required: true
    default: ''
  token:
    required: true
    default: ''
  pr_number:
    required: false
    default: ''
  slack_color:
    required: false
    default: ''
  title:
    required: false
    default: ''

runs:
  using: 'docker'                 # 도커 사용 명시
  image: 'Dockerfile'             # Dockerfile을 이용하여 이미지 생성
  args:
    - ${{ inputs.type }}
    - ${{ inputs.slack_webhook }}
    - ${{ inputs.token }}
    - ${{ inputs.pr_number}}
    - ${{ inputs.slack_color }}
    - ${{ inputs.title }}