on:
  pull_request:
    branches: [ main, release/*, develop ]
    types: [ closed ]

jobs:
  slack:
  if: 
    runs-on: ubuntu-latest
    steps:


    - name: test message
      uses: nooose/custom-slack-message@master
      with:
        type: pr
        slack_webhook: http://slack.webhook.url
        pr_number: ${{ github.event.number }}
