on: 
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0

      - name: ls
        run: ls -lR

      - name: Print commits
        run: |
          for COMMIT in $(git rev-list ${{ github.event.before }}..${{ github.sha }}); do
              git checkout $COMMIT
              echo "run test"
          done

      # - name: slack message
      #   uses: nooose/custom-slack-message@master
      #   with:
      #     type: push
      #     slack_webhook: 
      #     token: 
      #     slack_color: ${{ job.status }}
