on:
  pull_request:
    branches: [ main, release/*, develop ]
    types: [ closed ]

jobs:
  slack:
  if: 
    runs-on: ubuntu-latest
    steps:
    
      - name: slack message
        uses: nooose/custom-slack-message@master
        with:
          type: pr
          slack_webhook: 
          token: 
          slack_color: ${{ job.status }}
