on: 
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0


      - name: slack message
        uses: nooose/custom-slack-message@master
        with:
          type: push
          slack_webhook: 
          token: 
          slack_color: ${{ job.status }}
