on:
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: test message
      uses: nooose/custom-slack-message@master
      with:
        SLACK_WEBHOOK: http://slack.webhook.url
        TYPE: PR
        PR_NUMBER: ${{ github.event.number }}
